name: CICD_Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create resource directory
        run: mkdir -p ./src/main/resources

      - name: Create application.yml
        run: echo ${{ secrets.APPLICATION_YML }} > ./src/main/resources/application.yml

      - name: Set up ENV
        run: echo "TIME=$(date "+%Y-%m-%d-%H-%M")" >> $GITHUB_ENV

      - name: Build and push the Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dny-be:${{ env.TIME }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dny-be:${{ env.TIME }}

      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            sudo docker rm -f dny-be-container
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dny-be:${{ env.TIME }}
            sudo docker run -d --name dny-be-container -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/dny-be:${{ env.TIME }}
            sudo docker image prune -f
